homepage: "https://github.com/cyberviser/Hancock"
language: python
vendor: "CyberViser"
primary_contact: "0ai@cyberviserai.com"
auto_ccs:
  - "0ai@cyberviserai.com"
vendor_ccs:
  - "cyberviser@proton.me"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
  - coverage
architectures:
  - x86_64
main_repo: "https://github.com/cyberviser/Hancock"
builds_per_day: 1
file_github_issue: true
